# Generated by Django 4.1.4 on 2022-12-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='categoris',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='info',
            name='creator',
        ),
    ]
