# Generated by Django 4.1.4 on 2022-12-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_rename_categoris_info_content_remove_info_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='author',
        ),
        migrations.RemoveField(
            model_name='info',
            name='content',
        ),
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
