# Generated by Django 4.1.4 on 2022-12-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_remove_info_author_remove_info_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='isodate',
            field=models.IntegerField(),
        ),
    ]
