# Generated by Django 4.1.4 on 2022-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_alter_info_isodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
